### ISSUE TITLE
百度翻译出问题，请问下是什么原因啊

### ISSUE THREAD

**Issue by bieshuohua503** [kgepachong/crawler#2]
Traceback (most recent call last):
  File ".\pre3.py", line 84, in <module>
    main()
  File ".\pre3.py", line 78, in main
    sign, acs_token = get_sign_and_token(query, gtk, lang)
  File ".\pre3.py", line 53, in get_sign_and_token
    sign = execjs.compile(baidu_js).call('e', query, gtk)
  File "D:\python38\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "D:\python38\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "D:\python38\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "D:\python38\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "D:\python38\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "D:\python38\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: TypeError: 'global' 未定义

**Comment by TRHX** [comment]
node 环境没配好吧

**Comment by wwfcnu** [comment]
我也遇到了，请问你解决了吗

**Comment by TRHX** [comment]
> 我也遇到了，请问你解决了吗

安装好 node，配置好环境

**Comment by wwfcnu** [comment]
> > 我也遇到了，请问你解决了吗
> 
> 安装好 node，配置好环境

我试了有道翻译，没有问题，环境应该没问题

**Comment by TRHX** [comment]
> > > 我也遇到了，请问你解决了吗
> > 
> > 
> > 安装好 node，配置好环境
> 
> 我试了有道翻译，没有问题，环境应该没问题

项目目录下打印一下 `execjs.get().name` 看看是不是 `Node.js (V8)`
